export const PROVISION_QUEUE = 'provision'
export const PROVISION_JOB = 'provision-site'
export const UPTIME_QUEUE = 'uptime'
export const UPTIME_JOB = 'uptime-probe'
export const SITE_UPDATE_QUEUE = 'site-update'
export const SITE_UPDATE_JOB = 'update-site'
